# Generated by Django 3.2.9 on 2021-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_email', models.EmailField(max_length=254)),
                ('bs_pwd', models.CharField(max_length=50)),
                ('bs_access_token', models.CharField(max_length=120)),
                ('bs_user_id', models.CharField(max_length=20)),
                ('bs_credits', models.IntegerField(null=True)),
            ],
        ),
    ]
