# Generated by Django 3.0.8 on 2021-12-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=120)),
                ('analysis_ref_id', models.CharField(max_length=20)),
                ('analysis_status', models.CharField(max_length=120)),
                ('analysis_description', models.TextField(blank=True, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bs_analysis_id', models.CharField(blank=True, max_length=120, null=True)),
                ('bs_analysis_status', models.CharField(blank=True, max_length=120, null=True)),
                ('bs_analysis_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basespace',
            fields=[
                ('bs_email', models.EmailField(max_length=254)),
                ('bs_pwd', models.CharField(max_length=50)),
                ('bs_access_token', models.CharField(max_length=120)),
                ('bs_user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('bs_credits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('bs_default_project', models.CharField(max_length=40)),
                ('bs_project_id', models.CharField(max_length=40)),
                ('project_type', models.CharField(max_length=40)),
                ('project_created_on', models.DateTimeField(auto_now_add=True)),
                ('bs_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basespace.Basespace')),
            ],
        ),
        migrations.CreateModel(
            name='Biosample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosample_id', models.CharField(max_length=40, null=True)),
                ('biosample_type', models.CharField(max_length=20, null=True)),
                ('biosample_name', models.CharField(max_length=120, null=True)),
                ('biosample_path', models.CharField(max_length=480, null=True)),
                ('library_id', models.CharField(max_length=40, null=True)),
                ('biosample_created_on', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basespace.Project')),
            ],
        ),
    ]
