# Generated by Django 3.2.9 on 2021-12-02 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_email', models.EmailField(max_length=254)),
                ('bs_pwd', models.CharField(max_length=50)),
                ('bs_access_token', models.CharField(max_length=120)),
                ('bs_user_id', models.CharField(max_length=20)),
                ('bs_credits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('bs_default_project', models.CharField(max_length=40)),
                ('bs_project_id', models.CharField(max_length=40)),
                ('project_type', models.CharField(max_length=40)),
                ('project_created_on', models.DateTimeField(auto_now_add=True)),
                ('bs_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basespace.basespace')),
            ],
        ),
        migrations.CreateModel(
            name='Biosample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosample_id', models.CharField(max_length=40, null=True)),
                ('biosample_type', models.CharField(max_length=20, null=True)),
                ('biosample_name', models.CharField(max_length=120, null=True)),
                ('biosample_path', models.CharField(max_length=480, null=True)),
                ('library_id', models.CharField(max_length=40, null=True)),
                ('biosample_created_on', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basespace.project')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('href', models.URLField()),
                ('name', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=1000)),
                ('version_number', models.CharField(max_length=100)),
                ('href_logo', models.URLField()),
                ('homepage_ri', models.URLField()),
                ('short_description', models.CharField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_status', models.CharField(max_length=1000)),
                ('is_billing_activated', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('classifications', models.CharField(choices=[('None', 'None'), ('Resequencing', 'Resequencing'), ('SmallRNA', 'SmallRNA'), ('TargetedSequencing', 'TargetedSequencing'), ('DeNovoAssembly', 'DeNovoAssembly'), ('RNASeq', 'RNASeq'), ('GeneFusionDetection', 'GeneFusionDetection'), ('ChiPSeq', 'ChiPSeq'), ('MethylSeq', 'MethylSeq'), ('Metagenomics', 'Metagenomics'), ('TumorNormal', 'TumorNormal'), ('VariantAnalysis', 'VariantAnalysis'), ('DifferentialExpression', 'DifferentialExpression'), ('Quality', 'Quality'), ('SyntheticLongReads', 'SyntheticLongReads'), ('Proteomics', 'Proteomics')], default=None, max_length=1000)),
                ('app_family_slug', models.CharField(max_length=2000)),
                ('app_version_slug', models.CharField(max_length=2000)),
                ('features', models.CharField(choices=[('None', 'None'), ('GrantInheritanceDisabled', 'GrantInheritanceDisabled'), ('IsAppRegisteredToPlatform', 'IsAppRegisteredToPlatform')], default=None, max_length=1000)),
                ('basespace_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basespace.basespace')),
            ],
        ),
    ]
