# Generated by Django 3.0.8 on 2021-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basespace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=120)),
                ('analysis_ref_id', models.CharField(max_length=20)),
                ('analysis_status', models.CharField(max_length=120)),
                ('analysis_description', models.TextField(blank=True, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bs_analysis_id', models.CharField(blank=True, max_length=120, null=True)),
                ('bs_analysis_status', models.CharField(blank=True, max_length=120, null=True)),
                ('bs_analysis_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
